In [32]:
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

In [33]:
from pathlib import Path
from getpass import getpass

import json
import pandas as pd
import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

In [68]:
# Assignment 3

## Research Question

How does relative humidity (RH) vary with air temperature (AMB_TEMP) in Taiwan?

## Data Source

Taiwan Ministry of Environment (MOENV) Open Data API

Dataset:
AQX_P_35

## Selected Variables

- AMB_TEMP (Air Temperature, °C)
- RH (Relative Humidity, %)

SyntaxError: invalid character '°' (U+00B0) (3305990844.py, line 16)

In [35]:
import getpass

API_KEY = getpass.getpass("Enter your MOENV API key: ")
print("API key loaded.")

Enter your MOENV API key: ··········
API key loaded.

In [36]:
url = "https://data.moenv.gov.tw/api/v2/aqx_p_35"

params = {
    "limit": 1000,
    "format": "json",
    "api_key": API_KEY,
}

response = requests.get(
    url,
    params=params,
    timeout=30,
    verify=False
)

response.raise_for_status()

payload = response.json()

print("HTTP status:", response.status_code)
print("Payload type:", type(payload))

HTTP status: 200
Payload type: <class 'list'>

In [37]:
if isinstance(payload, dict):
    print(payload.keys())

In [41]:
print(type(payload))

<class 'list'>

In [43]:
df = pd.DataFrame(payload)

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

df.head()

Shape: (1000, 9)

Columns:
['siteid', 'sitename', 'itemid', 'itemname', 'itemengname', 'itemunit', 'monitordate', 'concentration', 'county']

,siteid,sitename,itemid,itemname,itemengname,itemunit,monitordate,concentration,county
0,69,竹山,14,溫度,AMB_TEMP,℃,2026-10-07 21:00,25.3,南投縣
1,80,關山,38,相對濕度,RH,percent,2026-10-07 21:00,69,臺東縣
2,50,鳳山,38,相對濕度,RH,percent,2026-10-07 21:00,69,高雄市
3,49,仁武,14,溫度,AMB_TEMP,℃,2026-10-07 21:00,28.1,高雄市
4,88,臺灣大道,38,相對濕度,RH,percent,2026-10-07 21:00,63,臺中市

In [44]:
print(df.columns.tolist())
df.head()

['siteid', 'sitename', 'itemid', 'itemname', 'itemengname', 'itemunit', 'monitordate', 'concentration', 'county']

,siteid,sitename,itemid,itemname,itemengname,itemunit,monitordate,concentration,county
0,69,竹山,14,溫度,AMB_TEMP,℃,2026-10-07 21:00,25.3,南投縣
1,80,關山,38,相對濕度,RH,percent,2026-10-07 21:00,69,臺東縣
2,50,鳳山,38,相對濕度,RH,percent,2026-10-07 21:00,69,高雄市
3,49,仁武,14,溫度,AMB_TEMP,℃,2026-10-07 21:00,28.1,高雄市
4,88,臺灣大道,38,相對濕度,RH,percent,2026-10-07 21:00,63,臺中市

In [45]:
print(df["itemname"].unique())
print(df["itemengname"].unique())

['溫度' '相對濕度']
['AMB_TEMP' 'RH']

In [46]:
wind_df = df[
    df["itemengname"] == "WIND_SPEED"
].copy()

wind_df.head()

Empty DataFrame
Columns: [siteid, sitename, itemid, itemname, itemengname, itemunit, monitordate, concentration, county]
Index: []

In [49]:
print(df.columns.tolist())
df.head()

['siteid', 'sitename', 'itemid', 'itemname', 'itemengname', 'itemunit', 'monitordate', 'concentration', 'county']

,siteid,sitename,itemid,itemname,itemengname,itemunit,monitordate,concentration,county
0,69,竹山,14,溫度,AMB_TEMP,℃,2026-10-07 21:00,25.3,南投縣
1,80,關山,38,相對濕度,RH,percent,2026-10-07 21:00,69,臺東縣
2,50,鳳山,38,相對濕度,RH,percent,2026-10-07 21:00,69,高雄市
3,49,仁武,14,溫度,AMB_TEMP,℃,2026-10-07 21:00,28.1,高雄市
4,88,臺灣大道,38,相對濕度,RH,percent,2026-10-07 21:00,63,臺中市

In [51]:
print(sorted(df["itemengname"].unique()))

['AMB_TEMP', 'RH']

In [57]:
temp_df = df[
    df["itemengname"] == "AMB_TEMP"
].copy()

print(temp_df.shape)

(490, 9)

In [61]:
temp_df = df[
    df["itemengname"] == "AMB_TEMP"
].copy()

temp_df.head()
rh_df = df[
    df["itemengname"] == "RH"
].copy()

rh_df.head()

,siteid,sitename,itemid,itemname,itemengname,itemunit,monitordate,concentration,county
1,80,關山,38,相對濕度,RH,percent,2026-10-07 21:00,69,臺東縣
2,50,鳳山,38,相對濕度,RH,percent,2026-10-07 21:00,69,高雄市
4,88,臺灣大道,38,相對濕度,RH,percent,2026-10-07 21:00,63,臺中市
6,59,屏東,38,相對濕度,RH,percent,2026-10-07 21:00,79,屏東縣
7,51,大寮,38,相對濕度,RH,percent,2026-10-07 21:00,79,高雄市

In [62]:
print("Temperature Shape:", temp_df.shape)

print("\nMissing Values:")
print(temp_df.isna().sum())

print("\nData Types:")
print(temp_df.dtypes)
print("RH Shape:", rh_df.shape)

print("\nMissing Values:")
print(rh_df.isna().sum())

print("\nData Types:")
print(rh_df.dtypes)

Temperature Shape: (490, 9)

Missing Values:
siteid           0
sitename         0
itemid           0
itemname         0
itemengname      0
itemunit         0
monitordate      0
concentration    0
county           0
dtype: int64

Data Types:
siteid           object
sitename         object
itemid           object
itemname         object
itemengname      object
itemunit         object
monitordate      object
concentration    object
county           object
dtype: object
RH Shape: (510, 9)

Missing Values:
siteid           0
sitename         0
itemid           0
itemname         0
itemengname      0
itemunit         0
monitordate      0
concentration    0
county           0
dtype: int64

Data Types:
siteid           object
sitename         object
itemid           object
itemname         object
itemengname      object
itemunit         object
monitordate      object
concentration    object
county           object
dtype: object

In [64]:
temp_df["concentration"] = pd.to_numeric(
    temp_df["concentration"],
    errors="coerce"
)

rh_df["concentration"] = pd.to_numeric(
    rh_df["concentration"],
    errors="coerce"
)

In [65]:
temp_df["concentration"].describe()
rh_df["concentration"].describe()

count    503.000000
mean      63.894632
std        8.297196
min       44.000000
25%       58.000000
50%       63.000000
75%       69.000000
max       92.000000
Name: concentration, dtype: float64

In [66]:
temp_df.head(10)
rh_df.head(10)

,siteid,sitename,itemid,itemname,itemengname,itemunit,monitordate,concentration,county
1,80,關山,38,相對濕度,RH,percent,2026-10-07 21:00,69.0,臺東縣
2,50,鳳山,38,相對濕度,RH,percent,2026-10-07 21:00,69.0,高雄市
4,88,臺灣大道,38,相對濕度,RH,percent,2026-10-07 21:00,63.0,臺中市
6,59,屏東,38,相對濕度,RH,percent,2026-10-07 21:00,79.0,屏東縣
7,51,大寮,38,相對濕度,RH,percent,2026-10-07 21:00,79.0,高雄市
9,85,大城,38,相對濕度,RH,percent,2026-10-07 21:00,73.0,彰化縣
12,72,埔里,38,相對濕度,RH,percent,2026-10-07 21:00,81.0,南投縣
14,70,永和,38,相對濕度,RH,percent,2026-10-07 21:00,66.0,新北市
15,67,三重,38,相對濕度,RH,percent,2026-10-07 21:00,54.0,新北市
16,62,臺東,38,相對濕度,RH,percent,2026-10-07 21:00,67.0,臺東縣

In [67]:
RAW_DIR = Path("data/raw")
RAW_DIR.mkdir(parents=True, exist_ok=True)

RAW_FILE = RAW_DIR / "aqx_p_35_sample.json"

with open(RAW_FILE, "w", encoding="utf-8") as f:
    json.dump(
        payload,
        f,
        ensure_ascii=False,
        indent=2
    )

print("Saved:", RAW_FILE)

Saved: data/raw/aqx_p_35_sample.json